services:
    python-tests:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: python-pipeline-tests
        environment:
            PYTHONUNBUFFERED: "1"
        network_mode: "bridge"
#        entrypoint: ["pytest", "-s", "--log-level=DEBUG"] # Uncomment to run tests with logging
