name: Python Test Suite

on:
    push:
        branches:
            - main  # Trigger this action on pushes to the 'main' branch
            - master # Trigger this action on pushes to the 'master' branch
    pull_request:
        branches:
            - main  # Trigger this action on pull requests targeting the 'main' branch
            - master # Trigger this action on pull requests targeting the 'master' branch

jobs:
    test:
        runs-on: ubuntu-latest # Use the latest version of the Ubuntu runner

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3  # This checks out the repository's code to the runner

            -   name: Set up Python
                uses: actions/setup-python@v4  # Set up a Python 3.12 environment
                with:
                  python-version: 3.12

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt  # Install the dependencies from your requirements.txt file

            -   name: Run tests with pytest
                run: |
                    pytest --maxfail=1 --disable-warnings -q  # Run tests with pytest, stopping after the first failure
